---
title: "SNAPP Case Study Analysis"
author: "Meghan Fletcher"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading the necessary packages
library(tidyverse)
library(googlesheets4)
library(here)
library(janitor)

#for text mining open responses
library(tidytext)
library(textdata)
library(ggwordcloud)
```

```{r}
#gs4_auth() # Run this in console with your email address. It allow R to access your google sheets
```

# Looking at the data one column at a time

```{r}
# Pull in the data from your google spreadsheets
kathy_lobster <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1gcmZufdNmc1KX9bKyduCYkHMT1ovdSea97GFdLcLv7Q/edit#gid=1070941345", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

eurich_KiribatiClam <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/10nq_klt68puKO2f1huE-mJO4EcgeLpYdijEz6gP-pyk/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names() #%>%
  #remove_empty(which = c("rows", "cols")) 
  #not sure if the remove will be best when analyzing multiple sheets

dickey_collas_EUR <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/18QVfptmhVlS-S0C_rUJVZ2vFbnMAEyCE7v0MIjVd1NU/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


#aguion_barnacle <-read_sheet(ss = #"https://docs.google.com/spreadsheets/d/1n6GKgX3_JklLeqoWgXetbgkx9gO6l8IE/edit?rtpof=true", 
#                           sheet = "S4_ResilienceAttributes",
#                           range = "A6:T7",
#                           col_names = TRUE,
#                           na = "",
#                           guess_max = 10000,
#                           trim_ws = TRUE,
#                           col_types = "c"
#                           ) %>%
#  as_tibble() %>%
#  clean_names()


hollowed_kasperski_BeringSea <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/180-RTmWdELLWcqLHxqmhCXOthjtdjxB_I_LZ38vUj98/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


#burden_sardine <-read_sheet(ss = #"https://docs.google.com/spreadsheets/d/15EGC7TPV_nvKhOAoDi7bTJv1l3qlor_v/edit#gid=2051385825", 
#                           sheet = "S4_ResilienceAttributes",
#                           range = "A6:T7",
#                           col_names = TRUE,
#                           na = "",
#                           guess_max = 10000,
#                           trim_ws = TRUE,
#                           col_types = "c"
#                           ) %>%
#  as_tibble() %>%
#  clean_names()


free_crab <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/15ykQMYzJRbKwfeIFH1gr7mvNxskICya6qFrVZngPwGM/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


kleisner_jfi <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1p6Twr7QULIY4H7eCYAcSSXapYH1yMKe6jLMZ6TaBEYI/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


lau_png <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1tzobZdKlZIZSqvT7lXb54C3t7kS7nHgfQP7o2ArlybY/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


#westfall_msf <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1uz7nb_aJ2cPK8txdiOY9SWnHc5M45Rs2/edit#gid=1818956842", 
#                           sheet = "S4_ResilienceAttributes",
#                           range = "A6:T7",
#                           col_names = TRUE,
#                           na = "",
#                           guess_max = 10000,
#                           trim_ws = TRUE,
#                           col_types = "c"
#                           ) %>%
#  as_tibble() %>%
#  clean_names()


zhoa_moorea <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1JrmJCYFqrqJ4BQgT2i-3rnl2tt6ja2kZuUJc63HkrUQ/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:T7",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()
```

# Testing the analysis

```{r}
#Analyzing the data

#This is binding the response sheets together into one sheet so it will be easier to analyze
test_section_bind <- bind_rows(kathy_lobster, dickey_collas_EUR, eurich_KiribatiClam, free_crab, hollowed_kasperski_BeringSea, kleisner_jfi, lau_png, zhoa_moorea)

#This is filtering to a specific question so that the question can be analyzed
test_section_bind_filter1 <- test_section_bind %>%
  filter(question_id == "4.1.1.1")

# Analyzing a multiple choice questions performing  a count
s4q1_count <- count(test_section_bind_filter1, test_section_bind_filter1$score_1_4)

s4q1_plot <- ggplot(test_section_bind_filter1, aes(x = score_1_4)) +
  geom_bar() +
  labs(caption = test_section_bind_filter1$definition_questions[1], x = "Reponses", y = "Count", title = test_section_bind_filter1$definition_questions[1]) +
  theme_bw()

plot(s4q1_plot)
  #ggtitle(test_section4_bind_filter1$definition_questions[1]) 
  

s4_data_quality_count <- count(test_section_bind, test_section_bind$information_quality)

s4_mechanism <- count(test_section_bind, test_section_bind$does_the_mechanism_work_as_described_in_this_fishery_system)


# This is making bar graphs of the counts.
mechanism_plot <- ggplot(test_section_bind, aes(x = does_the_mechanism_work_as_described_in_this_fishery_system)) +
  geom_bar() +
  labs(x = "Does the mechanism work in the system?", y = "Count") +
  theme_bw()

s4_data_quality_plot <- ggplot(test_section_bind, aes(x = information_quality)) +
  geom_bar() +
  coord_flip() +
  labs(x = "Information Quality", y = "Count") +
  theme_bw()


#This calling the counts and plots to be displayed
s4q1_count
s4_data_quality_count
s4_mechanism
s4q1_plot #I'm having trouble getting the full question to render and it would be good to have the columns be the actual responses instead of just a,b,c.
mechanism_plot
s4_data_quality_plot
```

###############################################################################################################################################

# Section 4 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 4
##If all data column names are not int he same order/identical, then "x1, x2,..." will replace the column name making it difficult to perform anaylses

mills_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1gcmZufdNmc1KX9bKyduCYkHMT1ovdSea97GFdLcLv7Q/edit#gid=1070941345", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

eurich_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/10nq_klt68puKO2f1huE-mJO4EcgeLpYdijEz6gP-pyk/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

dc_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/18QVfptmhVlS-S0C_rUJVZ2vFbnMAEyCE7v0MIjVd1NU/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

hk_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/180-RTmWdELLWcqLHxqmhCXOthjtdjxB_I_LZ38vUj98/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


free_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/15ykQMYzJRbKwfeIFH1gr7mvNxskICya6qFrVZngPwGM/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

kleisner_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1p6Twr7QULIY4H7eCYAcSSXapYH1yMKe6jLMZ6TaBEYI/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

lau_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1tzobZdKlZIZSqvT7lXb54C3t7kS7nHgfQP7o2ArlybY/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

zhoa_s4 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1JrmJCYFqrqJ4BQgT2i-3rnl2tt6ja2kZuUJc63HkrUQ/edit#gid=1980661832", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A6:P61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()


s4_bind <- bind_rows(mills_s4, eurich_s4, dc_s4, hk_s4, free_s4, kleisner_s4, lau_s4, zhoa_s4) 


```


```{r}
#Information Quality Analysis

s4_data_quality_count <- count(s4_bind, s4_bind$information_quality)

s4_data_quality_plot <- ggplot(s4_bind, aes(x = information_quality)) +
  geom_bar() +
  coord_flip() +
  labs(x = "Informaiton Quality", y = "Count") +
  theme_bw()

s4_data_quality_count
s4_data_quality_plot

```


```{r}
# Analyzing if the mechanisms are generally working in the system

s4_mechanism_count <- count(s4_bind, s4_bind$does_the_mechanism_work_as_described_in_this_fishery_system)

s4_mechanism_plot <- ggplot(s4_bind, aes(x = does_the_mechanism_work_as_described_in_this_fishery_system)) + 
  geom_bar() +
  labs(x = "Does the mechanism works as described?", y = "Count") +
  theme_bw()

s4_mechanism_count
s4_mechanism_plot
```


```{r}
# This makes a graph of the scores of the different resilience attributes based on dimension

#Ecological
ecological_scores <- s4_bind %>% 
  filter(dimensions == "Ecological")

ecological_scores_count <- count(ecological_scores, ecological_scores$score_1_4)

ecological_scores_graph <- ggplot(ecological_scores, aes(x = score_1_4)) + 
  geom_bar() +
  labs(x = "Capacity Score", y = "Count") +
  theme_bw()

#Socioeconomic
socioeconomic_scores <- s4_bind %>% 
  filter(dimensions == "Social-economic")

socioeconomic_scores_count <- count(socioeconomic_scores, socioeconomic_scores$score_1_4)

socioeconomic_scores_graph <- ggplot(socioeconomic_scores, aes(x = score_1_4)) + 
  geom_bar() +
  labs(x = "Capacity Score", y = "Count") +
  theme_bw()

#Governance
governance_scores <- s4_bind %>% 
  filter(dimensions == "Governance-management")

governance_scores_count <- count(governance_scores, governance_scores$score_1_4)

governance_scores_graph <- ggplot(governance_scores, aes(x = score_1_4)) + 
  geom_bar() +
  labs(x = "Capacity Score", y = "Count") +
  theme_bw()


#Results:
ecological_scores_count
ecological_scores_graph

socioeconomic_scores_count
socioeconomic_scores_graph

governance_scores_count
governance_scores_graph


### I want to look at the means here but we will need to remove all NA values - this will make more sense once everyone has filled in their case studies and there are less NA values to think about omitting 
#Means of scores across dimensions
#mean(ecologcial_scores$score_1_4)
#mean(socioeconomic_scores$score_1_4)
#mean(governance_scores$score_1_4)

```


```{r echo=FALSE}
# This will be for testing text analysis

s4_notes_tokens <- s4_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s4_notes_wc <- s4_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s4_notes_no_stop_numeric <- s4_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s4_notes_100 <- s4_notes_no_stop_numeric %>%
  count(word) %>% #World liek to figure out how to remove numbers in this data column
  
  arrange(-n) %>%
  head(100)

s4_notes_cloud <- ggplot(data = s4_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s4_notes_cloud

```





